name: Release Workflow

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # so we can create/push branches

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks curl

      - name: Extract version
        run: |
          VERSION=${{ github.event.release.tag_name }}   # e.g. "v0.1-1"
          VERSION=${VERSION#v}                           # remove the "v" prefix -> "0.1-1"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compute SHA256
        run: |
          TARBALL_URL="https://github.com/${{ github.repository }}/archive/refs/tags/${{ github.event.release.tag_name }}.tar.gz"
          echo "Downloading tarball from $TARBALL_URL"
          SHA256=$(curl -L "$TARBALL_URL" | sha256sum | awk '{ print $1 }')
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Update rockspec
        run: |
          ROCKSPEC_FILE=$(ls rockspecs/lua-resty-aws-signature-*.rockspec)

          # Remove the skip_validation line if it exists
          sed -i '/skip_validation *= *true/d' "$ROCKSPEC_FILE"

          # Replace any 'md5 = ' line with 'sha256 = "<hash>",'
          sed -i "s|md5 = .*|sha256 = \"${SHA256}\",|" "$ROCKSPEC_FILE" || true

          # If a 'sha256 = ' line exists, replace it. Otherwise insert after 'url ='
          if grep -q 'sha256 = ' "$ROCKSPEC_FILE"; then
            sed -i "s|sha256 = .*|sha256 = \"${SHA256}\",|" "$ROCKSPEC_FILE"
          else
            sed -i "/url = .*/a\\    sha256 = \"${SHA256}\"," "$ROCKSPEC_FILE"
          fi

          echo "== Final rockspec =="
          cat "$ROCKSPEC_FILE"

      - name: Commit changes to new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-rockspec-${{ env.VERSION }}
          git add rockspecs/lua-resty-aws-signature-*.rockspec
          git commit -m "Remove skip_validation, add sha256 for v${{ env.VERSION }}"

      - name: Push to new branch
        run: |
          git push origin update-rockspec-${{ env.VERSION }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-rockspec-${{ env.VERSION }}
          base: main
          title: "Update rockspec for v${{ env.VERSION }} with SHA256"
          body: "Automatically generated PR to remove skip_validation and add sha256."

      - name: Build .src.rock
        run: |
          luarocks pack rockspecs/lua-resty-aws-signature-*.rockspec

      - name: Build precompiled .rock
        run: |
          luarocks make rockspecs/lua-resty-aws-signature-*.rockspec
          luarocks pack lua-resty-aws-signature

      - name: Lint the rockspec
        run: luarocks lint rockspecs/lua-resty-aws-signature-*.rockspec

      - name: Upload to LuaRocks
        run: |
          luarocks upload lua-resty-aws-signature-*.src.rock --api-key=${{ secrets.LUAROCKS_API_KEY }}
          luarocks upload lua-resty-aws-signature-*.rock --api-key=${{ secrets.LUAROCKS_API_KEY }}

      - name: Upload .rock & .src.rock to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lua-resty-aws-signature-*.src.rock
            lua-resty-aws-signature-*.rock