name: CI - Build & Test

on:
  pull_request: 
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (for multi-platform builds if needed)
        uses: docker/setup-buildx-action@v3

      - name: Build and test with Makefile
        run: |
          make test